### ISSUE TITLE
Docker agents launch issue

### ISSUE THREAD

**Issue by w4zir** [MultiAgentLearning/playground#14]
Getting the following error when running docker agents:
```
DOCKER_AGENT_AGENT_CLASS=a.docker.pommerman.simple_agent.agent.Agent \
python games/run_battle.py \
    --agents="random::null,random::null,random::null,docker::pommerman/test-agent"
```

Starting container...
Traceback (most recent call last):
File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
__import__(pkg_name)
File "/app/games/a/__init__.py", line 1, in <module>
from . import agents
File "/app/games/a/agents.py", line 9, in <module>
from tensorforce.agents import PPOAgent
ModuleNotFoundError: No module named 'tensorforce'
Starting the Game.
/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/scipy/misc/pilutil.py:480: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/scipy/misc/pilutil.py:483: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
localhost
1003
Traceback (most recent call last):
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/az/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/az/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/az/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/az/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/az/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connection.py", line 168, in connect
    conn = self._new_conn()
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connection.py", line 152, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f35c4335080>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1003): Max retries exceeded with url: /action (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35c4335080>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "games/run_battle.py", line 96, in <module>
    actions = env.act(obs)
  File "/home/az/git_repos/ml/rl/playground/games/a/pommerman/envs/v0.py", line 94, in act
    action = agent.act(obs[agent.agent_id], action_space=self.action_space)
  File "/home/az/git_repos/ml/rl/playground/games/a/agents.py", line 90, in act
    "action_space": pickle.dumps(action_space, protocol=0).decode("utf-8")
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1003): Max retries exceeded with url: /action (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35c4335080>: Failed to establish a new connection: [Errno 111] Connection refused',))
Stopping container..
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.30/containers/173409928b662f09dba9af5d7cc9a031eecd08645548ed1366d2e6b66be7627e?v=False&link=False&force=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/az/git_repos/ml/rl/playground/bomberman_proj/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: 173409928b662f09dba9af5d7cc9a031eecd08645548ed1366d2e6b66be7627e")

**Comment by w4zir** [comment]
works fine if I just run:

`DOCKER_AGENT_AGENT_CLASS=a.docker.pommerman.simple_agent.agent.Agent python games/run_battle.py`

**Comment by w4zir** [comment]
Yes I did, using:
`docker build -t pommerman/test-agent . -f games/a/docker/Dockerfile `

**Comment by cinjon** [comment]
Can you try now following the updated (and quick) README for docker: https://github.com/MultiAgentLearning/playground/tree/master/games/a/docker

**Comment by w4zir** [comment]
Yes, working fine now.
