### ISSUE TITLE
use docker_agent in Simple_faa_run.py.

### ISSUE THREAD

**Issue by BrainWWW** [MultiAgentLearning/playground#182]
i built the docker image successfully and then i use docker _agent in Simple_faa_run.py
error comes below:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\docker\api\client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "E:\anaconda\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.35/containers/6bc538aad90c191f4652476ad6769a6884039add2e0b086fbb06dc779ce0ba4e/start
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\anaconda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\anaconda\lib\site-packages\pommerman\agents\docker_agent.py", line 74, in _run_container
    environment=self._env_vars)
  File "E:\anaconda\lib\site-packages\docker\models\containers.py", line 772, in run
    container.start()
  File "E:\anaconda\lib\site-packages\docker\models\containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "E:\anaconda\lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "E:\anaconda\lib\site-packages\docker\api\container.py", line 1066, in start
    self._raise_for_status(res)
  File "E:\anaconda\lib\site-packages\docker\api\client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "E:\anaconda\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint lucid_minsky (b1a71f73bf80e4ba0f5f51e1cc4cd3c7ae16a79919067d43069f0babcc8d1905): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:10080:tcp:172.17.0.2:10080: input/output error")

```

**Comment by cinjon** [comment]
This appears to be docker not starting in time. Is this still an issue for you? Please reopen if it's the case.

**Comment by BrainWWW** [comment]
Thanks, I figure it out : )
