### ISSUE TITLE
pom_tf_battle errors out: unexpected keyword argument 'action'

### ISSUE THREAD

**Issue by b-hodges** [MultiAgentLearning/playground#191]
When running pom_tf_battle with no arguments it gives the following error:

```
Traceback (most recent call last):
  File ".../pommerman/venv/bin/pom_tf_battle", line 11, in <module>
    load_entry_point('pommerman==0.2.0', 'console_scripts', 'pom_tf_battle')()
  File ".../pommerman/venv/lib/python3.6/site-packages/pommerman/cli/train_with_tensorforce.py", line 139, in main
    runner.run(episodes=10, max_episode_timesteps=2000)
  File ".../pommerman/venv/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 104, in run
    state, terminal, step_reward = self.environment.execute(action=action)
TypeError: execute() got an unexpected keyword argument 'action'
```

**Comment by cinjon** [comment]
Closing due to inactivity. Please reopen if it's still an issue.
