### ISSUE TITLE
Unable to import games.a

### ISSUE THREAD

**Issue by activatedgeek** [MultiAgentLearning/playground#25]
I am unable to import `games.a` with the following error

```
Python 3.6.4 (default, Mar  9 2018, 23:15:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 6.2.1
Python 3.6.4 (default, Mar  9 2018, 23:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
import games
import games.a
Traceback (most recent call last):
  File "/Users/sanyamkapoor/Workspace/mlenv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-4f2a0d71ab86>", line 1, in <module>
    import games.a
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/sanyamkapoor/Workspace/src/github.com/MultiAgentLearning/playground/games/a/__init__.py", line 4, in <module>
    from . import pommerman
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/sanyamkapoor/Workspace/src/github.com/MultiAgentLearning/playground/games/a/pommerman/__init__.py", line 1, in <module>
    from . import envs
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/sanyamkapoor/Workspace/src/github.com/MultiAgentLearning/playground/games/a/pommerman/envs/__init__.py", line 1, in <module>
    from . import utility
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/sanyamkapoor/Workspace/src/github.com/MultiAgentLearning/playground/games/a/pommerman/envs/utility.py", line 8, in <module>
    from a.pommerman.characters import Flame
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'a'
```

Weirdly, everything works from the `run_battle.py`. Something has gone wrong with the packaging here.

**Comment by activatedgeek** [comment]
This was most likely a cyclic package import problem when running as a package v/s as a script.
